apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: vihanm0120/user:latest
          ports:
            - containerPort: 3002
          env:
            - name: DB_URL
              value: "mongodb+srv://sksv:sksvD@cluster0.zychm.mongodb.net/userDB?retryWrites=true&w=majority&appName=Cluster0"
            - name: JWT_SECRET
              value: "sksvDeveloper"
            - name: SMTP_SERVER
              value: "smtp-relay.brevo.com"
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_LOGIN
              value: "vihanganethusara00@gmail.com"
            - name: SMTP_KEY
              value: "xsmtpsib-..."
            - name: SMTP_KEY_NAME
              value: "quickbite"
            - name: STRIPE_SECRET_KEY
              value: "sk_test_..."

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002